
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DataProvider } from "./context/GlobalProvider";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DataProvider>
        <html lang="en">
        <body className={`${inter.className} bg-black h-screen sm:h-auto`}>
      <Providers>
        <div>
        {children}
        </div>
      </Providers>
        </body>
        </html>
    </DataProvider>
  );
}
